-- Synthetic fixture only. Roll back every row and notification.
begin;
do $$
declare a uuid; rid uuid; token text:=encode(extensions.gen_random_bytes(32),'hex'); receipt jsonb; d jsonb; f jsonb; latest uuid; original jsonb; v integer;
begin
 select user_id into a from public.admin_users limit 1;
 if a is null then raise exception 'test_admin_missing'; end if;
 receipt:=public.submit_viewing_request_v6(gen_random_uuid(),jsonb_build_object('name','看貨回饋功能驗證','phone','0991662697','region','台北市','purpose','self','category','ring','material_preferences',jsonb_build_array('diamond'),'budget','10000-30000','style','minimal','selected_product_id','r-01','selected_product_name','回饋測試商品','viewing_region','台北市中正區','preferred_viewing_time',now()+interval '20 days'),token);
 rid:=(receipt->>'id')::uuid;
 select to_jsonb(m) into original from public.match_requests m where id=rid;
 f:=jsonb_build_object('viewed_on',(now() at time zone 'Asia/Taipei')::date,'outcome','not_purchased','reasons',jsonb_build_array('style','over_budget'),'budget_min',10000,'budget_max',30000,'contact_preference','recommend','note','希望簡約款');
 begin perform public.customer_aftercare(rid,repeat('0',64)); raise exception 'WRONG_TOKEN_ALLOWED'; exception when insufficient_privilege then null; end;
 begin perform public.customer_save_feedback(rid,token,null,f); raise exception 'EARLY_FEEDBACK_ALLOWED'; exception when others then if sqlerrm<>'feedback_not_ready' then raise; end if; end;
 perform set_config('request.jwt.claim.sub',gen_random_uuid()::text,true);
 begin perform public.admin_aftercare(rid); raise exception 'UNAUTHORIZED_ADMIN_ALLOWED'; exception when insufficient_privilege then null; end;
 begin perform public.admin_save_feedback(rid,null,f); raise exception 'UNAUTHORIZED_WRITE_ALLOWED'; exception when insufficient_privilege then null; end;
 begin perform public.admin_save_request_meta(rid,-1,true,'test',false); raise exception 'UNAUTHORIZED_META_ALLOWED'; exception when insufficient_privilege then null; end;
 perform set_config('request.jwt.claim.sub',a::text,true);
 perform public.admin_process_request(rid,0,'checking','{}','INTERNAL_PRIVATE_PROCESS');
 perform public.admin_process_request(rid,1,'transferring','{"partner_store":"測試店"}','');
 perform public.admin_process_request(rid,2,'in_transit','{}','');
 perform public.admin_process_request(rid,3,'arrived',jsonb_build_object('arrived_on',(now() at time zone 'Asia/Taipei')::date,'viewing_store','測試店','store_address','測試地址'),'');
 d:=public.customer_request_v7(rid,token);
 if jsonb_array_length(d->'timeline')<>4 or d::text like '%INTERNAL_PRIVATE_PROCESS%' or not (d->'timeline' @> '[{"kind":"checking"},{"kind":"transferring"},{"kind":"arrived"}]'::jsonb) then raise exception 'COMPACT_TIMELINE_BROKEN'; end if;
 begin perform public.customer_request_v7(rid,repeat('0',64)); raise exception 'TIMELINE_WRONG_TOKEN_ALLOWED'; exception when insufficient_privilege then null; end;
 perform public.admin_invite_feedback(rid); perform public.admin_invite_feedback(rid);
 if (select count(*) from public.request_notifications where request_id=rid and details->>'purpose'='viewing_feedback')<>1 then raise exception 'DUPLICATE_INVITE'; end if;
 begin perform public.customer_save_feedback(rid,token,null,f||'{"budget_max":5000}'); raise exception 'BAD_BUDGET_ALLOWED'; exception when others then if sqlerrm<>'invalid_feedback' then raise; end if; end;
 begin perform public.customer_save_feedback(rid,token,null,f||'{"reasons":[]}'); raise exception 'NO_REASON_ALLOWED'; exception when others then if sqlerrm<>'invalid_feedback' then raise; end if; end;
 perform public.customer_save_feedback(rid,token,null,f);
 d:=public.admin_aftercare(rid); latest:=(d->'feedback'->>'id')::uuid;
 if d->'feedback'->>'source'<>'customer' or d->'followup'->>'status'<>'pending' then raise exception 'FEEDBACK_NOT_VISIBLE'; end if;
 begin perform public.admin_save_feedback(rid,null,f); raise exception 'STALE_FEEDBACK_ALLOWED'; exception when others then if sqlerrm<>'feedback_conflict' then raise; end if; end;
 v:=(d->'followup'->>'version')::integer;
 perform public.admin_save_followup(rid,v,'contacted',(now() at time zone 'Asia/Taipei')::date,'INTERNAL_PRIVATE_NOTE');
 begin perform public.admin_save_followup(rid,v,'closed',null,'stale'); raise exception 'STALE_FOLLOWUP_ALLOWED'; exception when others then if sqlerrm<>'version_conflict' then raise; end if; end;
 if not (public.admin_followup_queue('due',0)->'items' @> jsonb_build_array(jsonb_build_object('id',rid))) then raise exception 'DUE_QUEUE_MISSING'; end if;
 d:=public.customer_aftercare(rid,token);
 if d::text like '%INTERNAL%' or d ? 'events' or d ? 'followup' or d->'feedback' ? 'actor_id' then raise exception 'INTERNAL_DATA_LEAK'; end if;
 perform public.admin_save_feedback(rid,latest,f||'{"outcome":"purchased","reasons":[],"contact_preference":"none"}');
 d:=public.admin_aftercare(rid);
 if jsonb_array_length(d->'history')<>2 or d->'feedback'->>'source'<>'admin' or d->'followup'->>'next_contact_on' is not null then raise exception 'HISTORY_OR_OPT_OUT_BROKEN'; end if;
 v:=(d->'followup'->>'version')::integer;
 begin perform public.admin_save_followup(rid,v,'contacted',(now() at time zone 'Asia/Taipei')::date,'opted out'); raise exception 'OPT_OUT_DATE_ALLOWED'; exception when others then if sqlerrm<>'invalid_followup' then raise; end if; end;
 perform public.admin_save_followup(rid,v,'closed',null,'已完成');
 perform public.admin_save_request_meta(rid,-1,true,'測試回饋單',false);
 begin perform public.admin_save_request_meta(rid,0,false,'測試回饋單',true); raise exception 'REAL_REQUEST_ARCHIVE_ALLOWED'; exception when others then if sqlerrm<>'invalid_request_meta' then raise; end if; end;
 perform public.admin_save_request_meta(rid,0,true,'測試回饋單',true);
 if public.admin_requests_v7('0991662697','','',0,false)->>'total'<>'0' or public.admin_requests_v7('0991662697','','',0,true)->>'total'<>'1' then raise exception 'ARCHIVE_FILTER_BROKEN'; end if;
 perform public.admin_save_request_meta(rid,1,true,'測試回饋單',false);
 if public.admin_requests_v7('0991662697','','',0,false)->>'total'<>'1' then raise exception 'RESTORE_BROKEN'; end if;
 if original is distinct from (select to_jsonb(m) from public.match_requests m where id=rid) then raise exception 'ORIGINAL_CHANGED'; end if;
 if has_table_privilege('anon','public.viewing_feedback','select') or has_table_privilege('authenticated','public.request_followup_events','select') or has_function_privilege('anon','public.admin_save_feedback(uuid,uuid,jsonb)','execute') or has_function_privilege('authenticated','public.write_viewing_feedback(uuid,uuid,jsonb,text)','execute') then raise exception 'DIRECT_PRIVATE_ACCESS'; end if;
end $$;
select 'PASS: capability authorization, admin guards, budget/reason validation, conflict rejection, customer/admin history, private notes, opt-out, follow-up queue, soft-delete/restore, unchanged original request' as aftercare_test_result;
rollback;
