// Generated by scripts/sync-products.py; edit Excel or catalog/sync-config.json.
import type { JewelryProduct } from '../types/product'

const products: JewelryProduct[] = [
  {
    "id": "BR00005-BR102",
    "sku": "BR00005-BR102",
    "name": "日曜光芒黃鑽手鍊（Sunlight Halo Bracelet）",
    "category": "bracelet",
    "materials": [
      "diamond"
    ],
    "styleTags": [],
    "price": 210000,
    "images": [
      "assets/missdiamond/braclet/BR00006-BR102.jpg"
    ],
    "description": "當陽光落在黃鑽之上，\n那抹金黃色澤總能瞬間吸引目光。\n這款手鍊以天然黃鑽為視覺焦點，搭配環繞四周的白鑽設計，讓中央黃鑽顯得更加耀眼奪目。\n黃鑽象徵希望、財富與正向能量，\n不僅是一件珠寶，更是一種光芒與自信的展現。\n無論是出席重要場合、收藏珍藏，或作為人生重要時刻的紀念，\n都能留下令人難忘的璀璨記憶。",
    "featureTags": [
      "經典款",
      "紀念送禮",
      "輕盈舒適"
    ],
    "specifications": "材質：14KW｜主石：天然鑽｜主石重量：D:0.36cts｜配鑽：天然鑽｜配鑽重量：YD:12P:0.13cts\nSD46P:1.02cts(0.02)",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "天然鑽",
    "mainStoneWeight": "D:0.36cts",
    "accentStone": "天然鑽",
    "accentStoneWeight": "YD:12P:0.13cts\nSD46P:1.02cts(0.02)",
    "metal": "14KW",
    "chainMetal": null,
    "stock": null,
    "sourceStatus": "寄店家",
    "available": false,
    "unavailableReason": "商品資料確認中"
  },
  {
    "id": "BR00005-BR98",
    "sku": "BR00005-BR98",
    "name": "Art Deco 經典鑽石手鍊",
    "category": "bracelet",
    "materials": [
      "18k-white-gold",
      "diamond"
    ],
    "styleTags": [],
    "price": 70500,
    "images": [
      "assets/missdiamond/braclet/BR00005-BR98.jpg"
    ],
    "description": "不同於傳統滿鑽手鍊的華麗張揚，\n這款以梯鑽與圓鑽交錯排列，呈現出俐落而細膩的節奏感。\n光線在不同切面間流轉，展現低調卻難以忽視的精緻魅力。\n無論是上班、聚會或正式場合，都能自然融入穿搭之中。\n是一款歷久彌新、不易退流行的經典作品。",
    "featureTags": [
      "氣質搭配",
      "日常配戴",
      "層次疊戴"
    ],
    "specifications": "材質：18KW｜鍊材質：18KW｜主石：無｜配鑽：天然鑽｜配鑽重量：6D:0.18cts(0.03)\nTD7D:0.28cts(0.04)",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "無",
    "mainStoneWeight": null,
    "accentStone": "天然鑽",
    "accentStoneWeight": "6D:0.18cts(0.03)\nTD7D:0.28cts(0.04)",
    "metal": "18KW",
    "chainMetal": "18KW",
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": false,
    "unavailableReason": "商品資料確認中"
  },
  {
    "id": "BR00007-BR123",
    "sku": "BR00007-BR123",
    "name": "Aurora Hex 極光六角鑽石手鍊",
    "category": "bracelet",
    "materials": [
      "18k-white-gold",
      "diamond"
    ],
    "styleTags": [],
    "price": 76000,
    "images": [
      "assets/missdiamond/braclet/BR00007-BR123.jpg"
    ],
    "description": "真正耐看的珠寶，\n不是最耀眼，而是每天都想戴。\nAurora Hex 以六角幾何元素結合天然真鑽，\n讓光線在每一顆鑽石間自然流動。\n沒有誇張的設計，\n卻能在舉手投足之間散發細緻光芒。\n它適合陪伴妳上班、旅行、約會，\n也陪妳度過每一個平凡卻珍貴的日常。",
    "featureTags": [
      "經典款",
      "簡約百搭",
      "日常配戴"
    ],
    "specifications": "材質：18KW｜主石：無｜配鑽：天然鑽｜配鑽重量：24D:0.48cts(0.02)",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "無",
    "mainStoneWeight": null,
    "accentStone": "天然鑽",
    "accentStoneWeight": "24D:0.48cts(0.02)",
    "metal": "18KW",
    "chainMetal": null,
    "stock": null,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "BR00008-BR124",
    "sku": "BR00008-BR124",
    "name": "法式優雅鑽石手鍊",
    "category": "bracelet",
    "materials": [
      "diamond"
    ],
    "styleTags": [],
    "price": 60000,
    "images": [
      "assets/missdiamond/braclet/BR00008-BR124.jpg"
    ],
    "description": "有些珠寶，不需要張揚，就能讓人一眼感受到品味。\n這款手鍊以圓形、方形與欖圓元素巧妙交織，每一顆天然鑽石都像生活中的小亮點，在光線下閃耀著溫柔光芒。\n簡潔卻不單調，優雅卻不浮誇。\n它適合陪伴妳穿梭於工作、生活與旅行之間，讓每一次抬手，都流露出細緻而自信的氣質。",
    "featureTags": [
      "經典款",
      "簡約百搭",
      "氣質搭配"
    ],
    "specifications": "材質：9K｜主石：無｜配鑽：天然鑽｜配鑽重量：25D:0.50cts(0.02)",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "無",
    "mainStoneWeight": null,
    "accentStone": "天然鑽",
    "accentStoneWeight": "25D:0.50cts(0.02)",
    "metal": "9K",
    "chainMetal": null,
    "stock": null,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "b-02",
    "sku": "BR00009-PB225",
    "name": "光芒1克拉鑽石手環",
    "category": "bracelet",
    "materials": [
      "diamond"
    ],
    "styleTags": [
      "refined",
      "glamorous"
    ],
    "price": 262200,
    "images": [],
    "description": "耐看的珠寶，不需要過度張揚。\n這款約1克拉天然鑽石手環，以21顆天然鑽石整齊排列，讓光線隨著每一次手部動作自然流轉，展現細緻而優雅的光芒。\n14K白搭配鏤空結構，不僅降低整體重量，也提升配戴舒適度，讓精品珠寶能真正融入每天的生活。\n無論正式宴會、商務場合，或日常穿搭，都能低調展現成熟質感，是值得長久收藏的經典款式。",
    "featureTags": [
      "日常配戴",
      "層次疊戴",
      "輕盈舒適"
    ],
    "specifications": "材質：14KW｜配鑽：天然鑽｜配鑽重量：21D:1.21cts(0.05)",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": null,
    "mainStoneWeight": null,
    "accentStone": "天然鑽",
    "accentStoneWeight": "21D:1.21cts(0.05)",
    "metal": "14KW",
    "chainMetal": null,
    "stock": null,
    "sourceStatus": "寄店家",
    "available": false,
    "unavailableReason": "商品資料確認中"
  },
  {
    "id": "DP00005-DP331",
    "sku": "DP00005-DP331",
    "name": "心語之戀鑽石項鍊\n(Heart Whisper Diamond Necklace)",
    "category": "necklace",
    "materials": [
      "18k-white-gold",
      "diamond"
    ],
    "styleTags": [],
    "price": 70000,
    "images": [
      "assets/missdiamond/pendant/DP00005-DP331.jpg"
    ],
    "description": "三顆愛心天然鑽石垂墜排列，總重0.12ct，搭配10K白金墜飾與18K白金項鍊，展現優雅柔美的頸間光彩。浪漫而經典，適合作為紀念日與珍藏禮物。",
    "featureTags": [
      "氣質搭配",
      "紀念送禮",
      "愛心設計"
    ],
    "specifications": "材質：10K｜鍊材質：18KW｜主石：天然鑽｜主石重量：無｜配鑽：天然鑽｜配鑽重量：HRT3D:0.12cts(0.04)",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "天然鑽",
    "mainStoneWeight": "無",
    "accentStone": "天然鑽",
    "accentStoneWeight": "HRT3D:0.12cts(0.04)",
    "metal": "10K",
    "chainMetal": "18KW",
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": false,
    "unavailableReason": "商品資料確認中"
  },
  {
    "id": "DP00006-DP339",
    "sku": "DP00006-DP339",
    "name": "綻放花語鑽石項鍊\n(Blooming Flower Diamond Necklace)",
    "category": "necklace",
    "materials": [
      "18k-rose-gold",
      "diamond"
    ],
    "styleTags": [],
    "price": 55000,
    "images": [
      "assets/missdiamond/pendant/DP00006-DP339.jpg"
    ],
    "description": "四顆馬眼形天然鑽石組成優雅花朵造型，總重0.32ct，\n搭配18K玫瑰金墜飾與18K玫瑰金鍊條，展現細膩火彩與柔美氣質。\n適合日常配戴與紀念。",
    "featureTags": [
      "簡約百搭",
      "氣質搭配",
      "日常配戴"
    ],
    "specifications": "材質：18KR｜鍊材質：18KR｜主石：天然鑽｜主石重量：無｜配鑽：天然鑽｜配鑽重量：MQ4P:0.32cts(0.08)",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "天然鑽",
    "mainStoneWeight": "無",
    "accentStone": "天然鑽",
    "accentStoneWeight": "MQ4P:0.32cts(0.08)",
    "metal": "18KR",
    "chainMetal": "18KR",
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": false,
    "unavailableReason": "商品資料確認中"
  },
  {
    "id": "DP00007-DP139",
    "sku": "DP00007-DP139",
    "name": "星辰藍寶石項鍊\n(Starlight Sapphire Necklace)",
    "category": "necklace",
    "materials": [
      "18k-yellow-gold"
    ],
    "styleTags": [],
    "price": 25000,
    "images": [
      "assets/missdiamond/pendant/DP00007-DP139.jpg"
    ],
    "description": "三顆天然藍寶石排列於頸間，展現優雅而細膩的藍色光彩。\n搭配14K黃金墜飾與18K黃金鍊條，在簡約設計中展現低調質感，\n適合日常配戴與送禮收藏。",
    "featureTags": [
      "簡約百搭",
      "日常配戴",
      "輕盈舒適"
    ],
    "specifications": "材質：14KY｜鍊材質：18KY｜主石：無｜主石重量：無｜配鑽：藍寶｜配鑽重量：3D:0.12cts(0.04)",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "無",
    "mainStoneWeight": "無",
    "accentStone": "藍寶",
    "accentStoneWeight": "3D:0.12cts(0.04)",
    "metal": "14KY",
    "chainMetal": "18KY",
    "stock": 1,
    "sourceStatus": "售出",
    "available": false,
    "unavailableReason": "目前暫不提供看貨媒合"
  },
  {
    "id": "DP00008-DP220W",
    "sku": "DP00008-DP220W",
    "name": "Royal Heart 皇冠鑽石項鍊(白)",
    "category": "necklace",
    "materials": [
      "18k-white-gold",
      "diamond"
    ],
    "styleTags": [],
    "price": 25000,
    "images": [
      "assets/missdiamond/pendant/DP00008-DP220W.jpg"
    ],
    "description": "將心形與皇冠元素巧妙融合，主鑽鑲嵌於心型中央，搭配皇冠造型配鑽點綴，展現優雅而浪漫的氣息。\n0.10 克拉天然主鑽成為視覺焦點，搭配五顆配鑽襯托光彩，在低調中展現精緻質感。無論作為紀念日禮物、生日禮物，或送給值得珍惜的自己，都是充滿心意的選擇。",
    "featureTags": [
      "日常配戴",
      "紀念送禮",
      "愛心設計"
    ],
    "specifications": "材質：18KW｜鍊材質：18KW｜主石：天然鑽｜主石重量：D:0.10cts｜配鑽：天然鑽｜配鑽重量：5D:0.05cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "天然鑽",
    "mainStoneWeight": "D:0.10cts",
    "accentStone": "天然鑽",
    "accentStoneWeight": "5D:0.05cts",
    "metal": "18KW",
    "chainMetal": "18KW",
    "stock": 2,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "DP00009-DP220R",
    "sku": "DP00009-DP220R",
    "name": "Royal Heart 皇冠鑽石項鍊(玫瑰金)",
    "category": "necklace",
    "materials": [
      "18k-rose-gold",
      "18k-white-gold",
      "diamond"
    ],
    "styleTags": [],
    "price": 42000,
    "images": [
      "assets/missdiamond/pendant/DP00009-DP220R.jpg"
    ],
    "description": "將心形與皇冠元素巧妙融合，主鑽鑲嵌於心型中央，搭配皇冠造型配鑽點綴，展現優雅而浪漫的氣息。\n0.10 克拉天然主鑽成為視覺焦點，搭配五顆配鑽襯托光彩，在低調中展現精緻質感。無論作為紀念日禮物、生日禮物，或送給值得珍惜的自己，都是充滿心意的選擇。",
    "featureTags": [
      "日常配戴",
      "紀念送禮",
      "愛心設計"
    ],
    "specifications": "材質：18KR｜鍊材質：18KW｜主石：天然鑽｜主石重量：D:0.10cts｜配鑽：天然鑽｜配鑽重量：5D:0.05cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "天然鑽",
    "mainStoneWeight": "D:0.10cts",
    "accentStone": "天然鑽",
    "accentStoneWeight": "5D:0.05cts",
    "metal": "18KR",
    "chainMetal": "18KW",
    "stock": 2,
    "sourceStatus": "寄店家",
    "available": false,
    "unavailableReason": "商品資料確認中"
  },
  {
    "id": "DP00010-DP221W",
    "sku": "DP00010-DP221W",
    "name": "星月晨曦鑽石項鍊",
    "category": "necklace",
    "materials": [
      "18k-white-gold",
      "diamond"
    ],
    "styleTags": [],
    "price": 42000,
    "images": [
      "assets/missdiamond/pendant/DP00010-DP221W.jpg"
    ],
    "description": "每個人心中，都有一輪屬於自己的月亮。\n星月晨曦鑽石項鍊以溫柔的新月環抱璀璨鑽石，象徵陪伴、守護與希望。中央10分天然鑽石經由放射狀配鑽襯托，散發如星光般耀眼的光芒，而鍊身上的一顆小鑽，更像夜空中最閃耀的一顆星，低調卻令人難忘。\n無論是送給自己，紀念人生的重要時刻；或送給摯愛，傳遞陪伴與祝福，都能成為值得珍藏一生的珠寶。",
    "featureTags": [
      "氣質搭配",
      "日常配戴",
      "閃耀光澤"
    ],
    "specifications": "材質：18KW｜鍊材質：18KW｜主石：天然鑽｜主石重量：D:0.10cts｜配鑽：天然鑽｜配鑽重量：SD:1P:0.025cts\nSD:8:0.08cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "天然鑽",
    "mainStoneWeight": "D:0.10cts",
    "accentStone": "天然鑽",
    "accentStoneWeight": "SD:1P:0.025cts\nSD:8:0.08cts",
    "metal": "18KW",
    "chainMetal": "18KW",
    "stock": 2,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "DP00011-DP221R",
    "sku": "DP00011-DP221R",
    "name": "星月晨曦鑽石項鍊 玫瑰金",
    "category": "necklace",
    "materials": [
      "18k-rose-gold",
      "diamond"
    ],
    "styleTags": [],
    "price": 42000,
    "images": [
      "assets/missdiamond/pendant/DP00011-DP221R.jpg"
    ],
    "description": "每個人心中，都有一輪屬於自己的月亮。\n星月晨曦鑽石項鍊以溫柔的新月環抱璀璨鑽石，象徵陪伴、守護與希望。中央10分天然鑽石經由放射狀配鑽襯托，散發如星光般耀眼的光芒，而鍊身上的一顆小鑽，更像夜空中最閃耀的一顆星，低調卻令人難忘。\n無論是送給自己，紀念人生的重要時刻；或送給摯愛，傳遞陪伴與祝福，都能成為值得珍藏一生的珠寶。",
    "featureTags": [
      "氣質搭配",
      "日常配戴",
      "閃耀光澤"
    ],
    "specifications": "材質：18KR｜鍊材質：18KR｜主石：天然鑽｜主石重量：D:0.10cts｜配鑽：天然鑽｜配鑽重量：SD:1P:0.025cts\nSD:8:0.08cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "天然鑽",
    "mainStoneWeight": "D:0.10cts",
    "accentStone": "天然鑽",
    "accentStoneWeight": "SD:1P:0.025cts\nSD:8:0.08cts",
    "metal": "18KR",
    "chainMetal": "18KR",
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": false,
    "unavailableReason": "商品資料確認中"
  },
  {
    "id": "DP00012-DP115",
    "sku": "DP00012-DP115",
    "name": "Classic Solitaire 20 Diamond Necklace｜18K Gold\n20分天然鑽石放大台單鑽項鍊｜D/VS｜18K金",
    "category": "necklace",
    "materials": [
      "18k-white-gold",
      "diamond"
    ],
    "styleTags": [],
    "price": 45000,
    "images": [
      "assets/missdiamond/pendant/DP00012-DP115.jpg"
    ],
    "description": "有些人追求的是更大的克拉數，有些人則更在意整體的配戴效果。\n\n採用放大台設計，透過精準的比例配置，讓 20 分天然鑽石擁有接近 30 分鑽石的視覺存在感，兼顧美感與預算。\n\n沒有過度繁複的裝飾，將焦點留給天然鑽石本身，展現經典耐看的珠寶魅力。無論是送給自己的人生紀念，或作為重要禮物，都能陪伴每一個值得珍藏的時刻。",
    "featureTags": [
      "經典款",
      "俐落風格",
      "閃耀光澤"
    ],
    "specifications": "材質：18KW｜鍊材質：無｜主石：天然鑽｜主石重量：D:0.20cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "天然鑽",
    "mainStoneWeight": "D:0.20cts",
    "accentStone": null,
    "accentStoneWeight": null,
    "metal": "18KW",
    "chainMetal": "無",
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "DP00013-DP119",
    "sku": "DP00013-DP119",
    "name": "經典四爪放大單鑽墜飾｜12分天然鑽石",
    "category": "necklace",
    "materials": [
      "18k-white-gold",
      "diamond"
    ],
    "styleTags": [],
    "price": 25000,
    "images": [
      "assets/missdiamond/pendant/DP00013-DP119.jpg"
    ],
    "description": "經典之所以經典，是因為它歷久彌新。\n\n採用最受歡迎的四爪單鑽設計，以18K白金襯托12分天然鑽石，讓光線自然穿透，展現晶瑩剔透的火彩。D色高白等級搭配SI淨度，在價格與品質之間取得理想平衡，是許多人入手天然鑽石珠寶的熱門選擇。\n\n無論日常穿搭、上班、約會或重要聚會，都能為整體造型增添細緻光采。簡潔俐落的設計，也讓它成為送給自己或重要之人的經典禮物。",
    "featureTags": [
      "經典款",
      "簡約百搭",
      "日常配戴"
    ],
    "specifications": "材質：18KW｜鍊材質：無｜主石：天然鑽｜主石重量：D:0.12cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "天然鑽",
    "mainStoneWeight": "D:0.12cts",
    "accentStone": null,
    "accentStoneWeight": null,
    "metal": "18KW",
    "chainMetal": "無",
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "DP00014-DP132",
    "sku": "DP00014-DP132",
    "name": "3分天然鑽石愛心項鍊14K",
    "category": "necklace",
    "materials": [
      "diamond"
    ],
    "styleTags": [],
    "price": 23500,
    "images": [
      "assets/missdiamond/pendant/DP00014-DP132.jpg"
    ],
    "description": "愛心，不只是浪漫，更代表著陪伴、守護與珍惜。\n\n將天然鑽石鑲嵌於愛心中央，以簡潔俐落的設計呈現細膩光澤，沒有過多裝飾，讓珠寶自然融入生活。\n\n無論送給自己，提醒自己值得被珍惜；或送給重要的人，都是一份充滿心意且歷久彌新的禮物。",
    "featureTags": [
      "經典款",
      "日常配戴",
      "愛心設計"
    ],
    "specifications": "材質：14KW｜鍊材質：無｜主石：天然鑽｜主石重量：D:0.03cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "天然鑽",
    "mainStoneWeight": "D:0.03cts",
    "accentStone": null,
    "accentStoneWeight": null,
    "metal": "14KW",
    "chainMetal": "無",
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "DP00015-DP136",
    "sku": "DP00015-DP136",
    "name": "Dancing Diamond 跳動鑽石項鍊",
    "category": "necklace",
    "materials": [
      "diamond"
    ],
    "styleTags": [],
    "price": 18000,
    "images": [
      "assets/missdiamond/pendant/DP00015-DP136.jpg"
    ],
    "description": "有些珠寶，不需要華麗，就能令人一眼難忘。\n這款 Dancing Diamond 跳動鑽石項鍊，以極簡圓形外框包覆中央10分天然鑽石。當妳走路、呼吸或轉身時，中央鑽石會隨著細微動作自然擺動，讓光線持續折射，散發比一般固定式鑽石更加靈動耀眼的火彩。\n9K白金搭配簡潔流暢的設計，展現現代女性低調、自信且耐看的品味。無論日常穿搭、上班、約會或送禮，都能成為長久陪伴的經典珠寶。",
    "featureTags": [
      "經典款",
      "簡約百搭",
      "日常配戴"
    ],
    "specifications": "材質：9K｜鍊材質：無｜主石：天然鑽｜主石重量：D:0.10cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "天然鑽",
    "mainStoneWeight": "D:0.10cts",
    "accentStone": null,
    "accentStoneWeight": null,
    "metal": "9K",
    "chainMetal": "無",
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "DP00016-DP154R",
    "sku": "DP00016-DP154R",
    "name": "晨曦經典 10分天然鑽石項鍊｜18K玫瑰金",
    "category": "necklace",
    "materials": [
      "18k-rose-gold",
      "diamond"
    ],
    "styleTags": [],
    "price": 35000,
    "images": [
      "assets/missdiamond/pendant/DP00016-DP154R.jpg"
    ],
    "description": "有些美，不需要過多裝飾。\n晨曦經典 10分天然鑽石項鍊以最經典的六爪鑲嵌，將10分天然鑽石穩固托起，讓光線能充分進入鑽石，每個角度都散發自然火彩。\n18K玫瑰金溫潤細膩的色澤，讓整體更加柔美優雅，不論單獨佩戴，或與其他項鍊層次搭配，都能展現恰到好處的精緻感。\n它不是最張揚的一件珠寶，卻是最容易陪伴妳走過每一天的一件作品。",
    "featureTags": [
      "經典款",
      "簡約百搭",
      "氣質搭配"
    ],
    "specifications": "材質：18KR｜鍊材質：18KR｜主石：天然鑽｜主石重量：D:0.10cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "天然鑽",
    "mainStoneWeight": "D:0.10cts",
    "accentStone": null,
    "accentStoneWeight": null,
    "metal": "18KR",
    "chainMetal": "18KR",
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "DP00017-DP155W",
    "sku": "DP00017-DP155W",
    "name": "晨曦經典 10分天然鑽石項鍊｜18K白",
    "category": "necklace",
    "materials": [
      "18k-white-gold",
      "diamond"
    ],
    "styleTags": [],
    "price": 35000,
    "images": [
      "assets/missdiamond/pendant/DP00017-DP155W.jpg"
    ],
    "description": "有些美，不需要過多裝飾。\n晨曦經典 10分天然鑽石項鍊以最經典的六爪鑲嵌，將10分天然鑽石穩固托起，讓光線能充分進入鑽石，每個角度都散發自然火彩。\n18K白溫潤細膩的色澤，讓整體更加柔美優雅，不論單獨佩戴，或與其他項鍊層次搭配，都能展現恰到好處的精緻感。\n它不是最張揚的一件珠寶，卻是最容易陪伴妳走過每一天的一件作品。",
    "featureTags": [
      "經典款",
      "簡約百搭",
      "氣質搭配"
    ],
    "specifications": "材質：18KW｜鍊材質：18KW｜主石：天然鑽｜主石重量：D:0.10cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "天然鑽",
    "mainStoneWeight": "D:0.10cts",
    "accentStone": null,
    "accentStoneWeight": null,
    "metal": "18KW",
    "chainMetal": "18KW",
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "DP00018-DP2553",
    "sku": "DP00018-DP2553",
    "name": "心語光芒 愛心鑽石項鍊｜18K白金",
    "category": "necklace",
    "materials": [
      "18k-white-gold",
      "diamond"
    ],
    "styleTags": [],
    "price": 35000,
    "images": [
      "assets/missdiamond/pendant/DP00018-DP2553.jpg"
    ],
    "description": "愛，不一定需要轟轟烈烈。\n有時，只需要一顆簡單的心，就足以表達最深的情感。\n這款心語光芒 愛心鑽石項鍊，以14顆天然鑽石勾勒出鏤空愛心輪廓，象徵愛與陪伴永遠留存在心中。每一顆鑽石都代表一份真心，細膩排列後形成柔和卻耀眼的光芒。\n18K白金散發純淨光澤，讓整體設計更加耐看，不論是送給摯愛、家人、女兒，或是送給努力生活的自己，都能成為值得珍藏的紀念。\n有些禮物，代表的是一句說不出口的——我一直都在。",
    "featureTags": [
      "經典款",
      "氣質搭配",
      "日常配戴"
    ],
    "specifications": "材質：18KW｜配鑽：天然鑽｜配鑽重量：14D:0.12cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": null,
    "mainStoneWeight": null,
    "accentStone": "天然鑽",
    "accentStoneWeight": "14D:0.12cts",
    "metal": "18KW",
    "chainMetal": null,
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "DP00019-DP268",
    "sku": "DP00019-DP268",
    "name": "星語流光 五鑽垂墜項鍊｜18K白金",
    "category": "necklace",
    "materials": [
      "18k-white-gold",
      "diamond"
    ],
    "styleTags": [],
    "price": 25000,
    "images": [
      "assets/missdiamond/pendant/DP00019-DP268.jpg"
    ],
    "description": "有些光芒，不是耀眼，而是細水長流。\n星語流光 五鑽垂墜項鍊以五顆天然鑽石依序排列，如同人生一路累積的美好時刻，也像夜空中連成一線的星光，低調卻始終閃耀。\n垂墜式設計讓項鍊隨著動作自然擺動，增添細緻光澤，同時修飾頸部比例，使整體造型更加優雅修長。\n18K白金搭配極簡設計，沒有多餘裝飾，卻能陪伴妳從日常到重要時刻，成為歷久彌新的經典作品。",
    "featureTags": [
      "簡約百搭",
      "氣質搭配",
      "層次疊戴"
    ],
    "specifications": "材質：18KW｜鍊材質：18KW｜配鑽：天然鑽｜配鑽重量：5D:0.05cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": null,
    "mainStoneWeight": null,
    "accentStone": "天然鑽",
    "accentStoneWeight": "5D:0.05cts",
    "metal": "18KW",
    "chainMetal": "18KW",
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "DP00020-DP57",
    "sku": "DP00020-DP57",
    "name": "流光擁抱鑽石項鍊｜15分天然鑽石｜14K",
    "category": "necklace",
    "materials": [
      "diamond"
    ],
    "styleTags": [],
    "price": 28500,
    "images": [
      "assets/missdiamond/pendant/DP00020-DP57.jpg"
    ],
    "description": "真正的光芒，不需要刻意炫耀。\n流光擁抱鑽石項鍊以柔和流線包覆著15分天然鑽石，就像一雙溫柔的手，守護著最珍貴的信念與回憶。\n設計沒有多餘的裝飾，而是透過簡潔的線條，讓鑽石自然成為視覺焦點。每一次光線流轉，都散發出內斂而自信的光彩。\n它適合每天陪伴妳，無論是工作、約會或旅行，都能低調地展現品味，讓珠寶成為生活的一部分，而非只屬於特別的日子。",
    "featureTags": [
      "經典款",
      "簡約百搭",
      "氣質搭配"
    ],
    "specifications": "材質：14KW｜主石：天然鑽｜主石重量：D:0.15cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "天然鑽",
    "mainStoneWeight": "D:0.15cts",
    "accentStone": null,
    "accentStoneWeight": null,
    "metal": "14KW",
    "chainMetal": null,
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "c-01",
    "sku": "DR00001-PD520",
    "name": "銀河繁星線戒\nGalaxy Stardust Ring",
    "category": "ring",
    "materials": [
      "diamond"
    ],
    "styleTags": [
      "minimal",
      "neutral"
    ],
    "price": 557600,
    "images": [
      "assets/missdiamond/band ring/DR00001-PD520.jpg",
      "assets/missdiamond/band ring/DR00001-PD520-2.jpg"
    ],
    "description": "這款寬版滿鑽戒指以俐落大器的線條呈現現代珠寶風格。\n整體採用天然鑽石密鑲鋪排，讓光線從不同角度折射出耀眼火彩。\n厚實而流暢的戒身設計，兼具舒適度與存在感，\n是一款能展現自信與品味的經典珠寶作品。",
    "featureTags": [
      "輕盈舒適",
      "寬版設計",
      "細緻鑲嵌"
    ],
    "specifications": "材質：14KW｜鍊材質：10K｜主石：無｜主石重量：無｜配鑽：天然鑽｜配鑽重量：15D:2.78cts(0.18)\n8D:0.06cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "無",
    "mainStoneWeight": "無",
    "accentStone": "天然鑽",
    "accentStoneWeight": "15D:2.78cts(0.18)\n8D:0.06cts",
    "metal": "14KW",
    "chainMetal": "10K",
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "r-01",
    "sku": "DR00002-PD394",
    "name": "雙星閃耀鑽石戒指\n(Double Star Diamond Ring)",
    "category": "ring",
    "materials": [
      "diamond"
    ],
    "styleTags": [
      "refined",
      "minimal"
    ],
    "price": 93600,
    "images": [
      "assets/missdiamond/ring/DR00002-PD394.jpg",
      "assets/missdiamond/ring/DR00002-PD394-2.jpg"
    ],
    "description": "每個人心中，都有一顆想追逐的星。\n雙星閃耀鑽石戒指以兩顆交錯的星芒作為設計主軸，象徵夢想與陪伴，也代表生命中重要的人與自己並肩前行。\n戒身採用流線交叉設計，搭配細緻微鑲鑽石，讓光線隨著舉手投足自然流動。無論是日常穿搭、約會聚餐，或作為送給自己的紀念珠寶，都能在低調中展現專屬光芒。\n願每一次抬起手時，都能記得自己曾許下的願望。",
    "featureTags": [
      "日常配戴",
      "層次疊戴",
      "細緻鑲嵌"
    ],
    "specifications": "材質：14KW｜鍊材質：10K｜主石：無｜主石重量：無｜配鑽：天然鑽｜配鑽重量：34D:0.51cts(0.01)",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "無",
    "mainStoneWeight": "無",
    "accentStone": "天然鑽",
    "accentStoneWeight": "34D:0.51cts(0.01)",
    "metal": "14KW",
    "chainMetal": "10K",
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "c-02",
    "sku": "DR00003-DR464L",
    "name": "繁星微笑鑽石戒指\n(Star Smile Diamond Ring)",
    "category": "ring",
    "materials": [
      "18k-rose-gold",
      "diamond"
    ],
    "styleTags": [
      "sweet",
      "refined"
    ],
    "price": 40000,
    "images": [
      "assets/missdiamond/band ring/DR00003-DR464L.jpg",
      "assets/missdiamond/band ring/DR00003-DR464L-2.jpg"
    ],
    "description": "",
    "featureTags": [
      "氣質搭配",
      "日常配戴",
      "層次疊戴"
    ],
    "specifications": "材質：18KR｜鍊材質：10K｜主石：無｜主石重量：無｜配鑽：天然鑽｜配鑽重量：13D:0.14cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "無",
    "mainStoneWeight": "無",
    "accentStone": "天然鑽",
    "accentStoneWeight": "13D:0.14cts",
    "metal": "18KR",
    "chainMetal": "10K",
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "r-02",
    "sku": "DR00004-LN09",
    "name": "流光鑽石戒指\n(Flow Diamond Ring)",
    "category": "ring",
    "materials": [
      "diamond"
    ],
    "styleTags": [
      "sweet",
      "designer"
    ],
    "price": 55000,
    "images": [
      "assets/missdiamond/ring/DR00004-LN09.jpg",
      "assets/missdiamond/ring/DR00004-LN09-2.jpg"
    ],
    "description": "光芒，不一定要耀眼奪目。\n這款流光鑽石戒指以柔和流線包覆中央鑽石，彷彿一道溫柔的光芒環繞守護著珍貴的心意。簡潔俐落的設計，讓鑽石成為視覺焦點，同時保有日常佩戴所需的舒適與耐看。\n0.10克拉天然鑽石在舉手投足間散發細緻火彩，搭配9K白金純淨色澤，無論上班、約會或日常穿搭，都能展現恰到好處的優雅氣質。\n\n獻給每一位認真生活的妳，讓平凡日子也擁有專屬的光芒。",
    "featureTags": [
      "簡約百搭",
      "氣質搭配",
      "日常配戴"
    ],
    "specifications": "材質：9K｜鍊材質：10K｜主石：天然鑽｜主石重量：無｜配鑽：天然鑽｜配鑽重量：D:0.10cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "天然鑽",
    "mainStoneWeight": "無",
    "accentStone": "天然鑽",
    "accentStoneWeight": "D:0.10cts",
    "metal": "9K",
    "chainMetal": "10K",
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "DR00005-DR590",
    "sku": "DR00005-DR590",
    "name": "綻放花語鑽石戒指\n(Blooming Flower Diamond Ring)",
    "category": "ring",
    "materials": [
      "18k-rose-gold",
      "diamond"
    ],
    "styleTags": [],
    "price": 98000,
    "images": [
      "assets/missdiamond/ring/DR00005-DR590.jpg",
      "assets/missdiamond/ring/DR00005-DR590-2.jpg"
    ],
    "description": "四顆馬眼形天然鑽石組成優雅花朵造型，總重0.34ct，搭配18K玫瑰金與扭轉戒身設計，展現柔美而細膩的光彩。適合日常配戴、送禮及紀念收藏。。",
    "featureTags": [
      "氣質搭配",
      "日常配戴",
      "紀念送禮"
    ],
    "specifications": "材質：18KR｜鍊材質：10K｜主石：無｜主石重量：無｜配鑽：天然鑽｜配鑽重量：MQ4P:0.34cts(0.085)",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "無",
    "mainStoneWeight": "無",
    "accentStone": "天然鑽",
    "accentStoneWeight": "MQ4P:0.34cts(0.085)",
    "metal": "18KR",
    "chainMetal": "10K",
    "stock": 1,
    "sourceStatus": "上架中",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "DR00006-DR588",
    "sku": "DR00006-DR588",
    "name": "心語三重奏鑽石戒指\n(Triple Heart Diamond Ring)",
    "category": "ring",
    "materials": [
      "diamond"
    ],
    "styleTags": [],
    "price": 85000,
    "images": [
      "assets/missdiamond/band ring/DR00006-DR588.jpg",
      "assets/missdiamond/band ring/DR00006-DR588-2.jpg"
    ],
    "description": "三顆愛心形天然鑽石排列於戒身中央，象徵愛、陪伴與珍惜。簡約俐落的線條搭配低做台設計，兼具舒適度與日常實用性，適合單戴或搭配其他戒指疊戴。",
    "featureTags": [
      "日常配戴",
      "愛心設計",
      "輕盈舒適"
    ],
    "specifications": "材質：10K｜主石：無｜主石重量：無｜配鑽：天然鑽｜配鑽重量：HRT3D:0.24cts(0.08)",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "無",
    "mainStoneWeight": "無",
    "accentStone": "天然鑽",
    "accentStoneWeight": "HRT3D:0.24cts(0.08)",
    "metal": "10K",
    "chainMetal": null,
    "stock": 1,
    "sourceStatus": "上架中",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "c-03",
    "sku": "DR00007-DSR01",
    "name": "V型鑽石線戒\n(V Diamond Band)",
    "category": "ring",
    "materials": [
      "diamond"
    ],
    "styleTags": [
      "designer",
      "neutral"
    ],
    "price": 20000,
    "images": [
      "assets/missdiamond/band ring/DR00007-DSR01.jpg",
      "assets/missdiamond/band ring/DR00007-DSR01-2.jpg"
    ],
    "description": "簡約俐落的V型線條搭配天然鑽石排列，展現細膩而優雅的光芒。輕盈舒適的設計適合日常配戴，也能作為婚戒、副戒或疊戴戒指，創造不同層次的搭配風格。",
    "featureTags": [
      "日常配戴",
      "層次疊戴",
      "輕盈舒適"
    ],
    "specifications": "材質：14KW｜主石：無｜主石重量：無｜配鑽：天然鑽｜配鑽重量：15D:0.10cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "無",
    "mainStoneWeight": "無",
    "accentStone": "天然鑽",
    "accentStoneWeight": "15D:0.10cts",
    "metal": "14KW",
    "chainMetal": null,
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "DR00008-RG92290",
    "sku": "DR00008-RG92290",
    "name": "星光鑽石排戒",
    "category": "ring",
    "materials": [
      "18k-white-gold",
      "diamond"
    ],
    "styleTags": [],
    "price": 33000,
    "images": [
      "assets/missdiamond/band ring/DR00008-RG92290.jpg",
      "assets/missdiamond/band ring/DR00008-RG92290-2.jpg"
    ],
    "description": "以 13 顆天然鑽石排列而成，總鑽重 0.15 克拉，低調中展現細膩光芒。\n簡潔俐落的戒身設計，適合作為日常配戴戒指，也能與其他戒款自由疊搭，創造屬於自己的珠寶風格",
    "featureTags": [
      "經典款",
      "簡約百搭",
      "日常配戴"
    ],
    "specifications": "材質：18KW｜主石：無｜主石重量：無｜配鑽：天然鑽｜配鑽重量：13D:0.15cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "無",
    "mainStoneWeight": "無",
    "accentStone": "天然鑽",
    "accentStoneWeight": "13D:0.15cts",
    "metal": "18KW",
    "chainMetal": null,
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "DR00009-DG1200",
    "sku": "DR00009-DG1200",
    "name": "璀璨鋪鑽寬版戒指",
    "category": "ring",
    "materials": [
      "diamond"
    ],
    "styleTags": [],
    "price": 302300,
    "images": [
      "assets/missdiamond/band ring/DR00009-DG1200.jpg",
      "assets/missdiamond/band ring/DR00009-DG1200-2.jpg"
    ],
    "description": "以 65 顆天然真鑽密集鋪鑲而成，總重達 1.60 克拉，展現耀眼且均勻的火光效果。\n\n寬版戒身搭配圓潤流線輪廓，兼具存在感與舒適度。無論單獨佩戴或作為造型主角，都能展現自信且大方的珠寶魅力。\n\n適合喜歡份量感、重視鑽石閃耀效果的配戴者。",
    "featureTags": [
      "日常配戴",
      "寬版設計",
      "細緻鑲嵌"
    ],
    "specifications": "材質：14KW｜主石：無｜主石重量：無｜配鑽：天然鑽｜配鑽重量：65D:1.60cts(0.024)",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "無",
    "mainStoneWeight": "無",
    "accentStone": "天然鑽",
    "accentStoneWeight": "65D:1.60cts(0.024)",
    "metal": "14KW",
    "chainMetal": null,
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "c-04",
    "sku": "DR00010-PD636",
    "name": "璀璨40分線戒",
    "category": "ring",
    "materials": [
      "diamond"
    ],
    "styleTags": [
      "glamorous",
      "refined"
    ],
    "price": 102900,
    "images": [
      "assets/missdiamond/band ring/DR00010-PD636.jpg",
      "assets/missdiamond/band ring/DR00010-PD636-2.jpg"
    ],
    "description": "有些幸福，不需要一句話。\n九顆天然鑽石依序排列，如同人生中一段段珍貴的回憶，串起愛情、成長、家庭與夢想。\n璀璨半圈鑽戒沒有誇張的造型，而是以最經典的半圈鑽設計，展現歷久彌新的優雅。\n無論是人生的重要紀念、周年禮物，或單純想送給努力生活的自己，它都能陪伴妳走過更多值得珍藏的時光。\n真正值得收藏的珠寶，不只是因為閃耀，而是因為它陪妳經歷人生。",
    "featureTags": [
      "經典款",
      "氣質搭配",
      "日常配戴"
    ],
    "specifications": "材質：14KW｜主石：無｜配鑽：天然鑽｜配鑽重量：9D:0.43cts(0.047)",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "無",
    "mainStoneWeight": null,
    "accentStone": "天然鑽",
    "accentStoneWeight": "9D:0.43cts(0.047)",
    "metal": "14KW",
    "chainMetal": null,
    "stock": 2,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "DR00011-PD668",
    "sku": "DR00011-PD668",
    "name": "璀璨10分線戒",
    "category": "ring",
    "materials": [
      "diamond"
    ],
    "styleTags": [],
    "price": 34900,
    "images": [
      "assets/missdiamond/band ring/DR00011-PD668.jpg",
      "assets/missdiamond/band ring/DR00011-PD668-2.jpg"
    ],
    "description": "有些珠寶，不需要太張揚。\n一枚細緻的線戒，能默默陪伴每天的生活。\n無論是上班、聚餐、旅行，或只是平凡的一天，\n鑽石細緻排列出的光澤，都能在舉手投足間增添自信與質感。\n它既可以成為人生第一枚鑽石戒指，也能作為未來疊戴收藏的開始。\n越簡單的設計，越能陪伴更長久。",
    "featureTags": [
      "簡約百搭",
      "日常配戴",
      "層次疊戴"
    ],
    "specifications": "材質：14KW｜配鑽：天然鑽｜配鑽重量：11D:0.11cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": null,
    "mainStoneWeight": null,
    "accentStone": "天然鑽",
    "accentStoneWeight": "11D:0.11cts",
    "metal": "14KW",
    "chainMetal": null,
    "stock": 2,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "DR00012-PD731",
    "sku": "DR00012-PD731",
    "name": "光芒50分三排鑽戒",
    "category": "ring",
    "materials": [
      "diamond"
    ],
    "styleTags": [],
    "price": 134200,
    "images": [
      "assets/missdiamond/band ring/DR00012-PD731.jpg",
      "assets/missdiamond/band ring/DR00012-PD731-2.jpg"
    ],
    "description": "有些珠寶，不需要一顆主鑽，就足以成為全場焦點。\n39顆天然鑽石細緻排列，讓光芒從每個角度自然綻放，形成比單顆鑽石更豐富、更有層次的視覺效果。\n它不像傳統單鑽戒指那樣強調一顆主石，而是以整體的璀璨感展現優雅氣質。無論是日常穿搭、正式聚會或重要紀念日，都能展現成熟而自信的品味。\n如果妳喜歡有存在感，又希望設計經典耐看的戒款，這款會是值得長久收藏的選擇。",
    "featureTags": [
      "簡約百搭",
      "層次疊戴",
      "輕盈舒適"
    ],
    "specifications": "材質：14KW｜配鑽：天然鑽｜配鑽重量：39D:0.56cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": null,
    "mainStoneWeight": null,
    "accentStone": "天然鑽",
    "accentStoneWeight": "39D:0.56cts",
    "metal": "14KW",
    "chainMetal": null,
    "stock": 2,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "DR00013-PD614",
    "sku": "DR00013-PD614",
    "name": "光采30分經典鑽戒",
    "category": "ring",
    "materials": [
      "diamond"
    ],
    "styleTags": [],
    "price": 144100,
    "images": [
      "assets/missdiamond/ring/DR00013-PD614.jpg",
      "assets/missdiamond/ring/DR00013-PD614-2.jpg"
    ],
    "description": "經典，往往來自最純粹的設計。\n這款以30分天然鑽石作為主石，搭配E Color高色澤等級，呈現乾淨透亮的光澤。兩側肩鑽細緻排列，不僅增加整體火光，也讓主鑽看起來更加立體耀眼。\n六爪鑲嵌是珠寶中最經典的設計之一，能穩固保護主鑽，同時讓更多光線進入鑽石，展現自然閃耀的火彩。\n不論作為求婚戒指、紀念日禮物，或犒賞自己的收藏珠寶，都能陪伴妳度過每一個重要時刻。",
    "featureTags": [
      "經典款",
      "日常配戴",
      "輕盈舒適"
    ],
    "specifications": "材質：14KW｜主石：天然鑽｜主石重量：D:0.30cts｜配鑽：天然鑽｜配鑽重量：12D:0.20cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "天然鑽",
    "mainStoneWeight": "D:0.30cts",
    "accentStone": "天然鑽",
    "accentStoneWeight": "12D:0.20cts",
    "metal": "14KW",
    "chainMetal": null,
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "r-03",
    "sku": "DR00014-PD804",
    "name": "光環30分鑽戒",
    "category": "ring",
    "materials": [
      "diamond"
    ],
    "styleTags": [
      "bold",
      "glamorous"
    ],
    "price": 72700,
    "images": [
      "assets/missdiamond/ring/DR00014-PD804.jpg",
      "assets/missdiamond/ring/DR00014-PD804-2.jpg",
      "assets/missdiamond/ring/DR00014-PD804-3.jpg"
    ],
    "description": "如果喜歡主鑽看起來更大、更耀眼，Halo 光環設計一直都是經典選擇。\n\n主鑽四周環繞一圈細緻天然鑽石，不僅提升整體亮度，也讓主鑽呈現更飽滿的視覺效果。搭配戒臂兩側的細鑽鑲嵌，讓光線從不同角度折射，每個轉動都散發迷人光芒。\n\n此款戒台適用30分至50分天然鑽石，可依需求搭配不同等級主鑽，兼具配戴美感與未來升級彈性，是求婚、紀念日及日常收藏都非常受歡迎的經典款式。",
    "featureTags": [
      "經典款",
      "日常配戴",
      "細緻鑲嵌"
    ],
    "specifications": "材質：14KW｜配鑽：天然鑽｜配鑽重量：34D:0.15cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": null,
    "mainStoneWeight": null,
    "accentStone": "天然鑽",
    "accentStoneWeight": "34D:0.15cts",
    "metal": "14KW",
    "chainMetal": null,
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "DR00015-PD783",
    "sku": "DR00015-PD783",
    "name": "星光經典六爪鑽戒",
    "category": "ring",
    "materials": [
      "diamond"
    ],
    "styleTags": [],
    "price": 114100,
    "images": [
      "assets/missdiamond/ring/DR00015-PD783.png"
    ],
    "description": "主鑽 0.33 克拉，搭配戒臂 22 顆小鑽、共 0.14 克拉，細緻排列於兩側，讓主鑽視覺更集中、同時增加整體閃耀感。戒台採 14K 金製作，戒臂線條纖細俐落，保留經典單鑽戒的乾淨比例，又比一般素面單鑽多一點精緻感。\n\n六爪鑲嵌讓主鑽輪廓完整呈現，從正面看有明顯聚焦效果；細版戒腳則讓整體不顯厚重，適合日常配戴，也很適合作為求婚戒、紀念戒或送給自己的第一只鑽戒。",
    "featureTags": [
      "經典款",
      "日常配戴",
      "紀念送禮"
    ],
    "specifications": "材質：14KW｜主石：天然鑽｜主石重量：D:0.30cts｜配鑽：天然鑽｜配鑽重量：22D:0.14cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "天然鑽",
    "mainStoneWeight": "D:0.30cts",
    "accentStone": "天然鑽",
    "accentStoneWeight": "22D:0.14cts",
    "metal": "14KW",
    "chainMetal": null,
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "DR00016-P305",
    "sku": "DR00016-P305",
    "name": "DR00016-P305",
    "category": "ring",
    "materials": [
      "diamond"
    ],
    "styleTags": [],
    "price": 123900,
    "images": [],
    "description": "",
    "featureTags": [],
    "specifications": "材質：14KW｜主石：天然鑽｜主石重量：D:0.30cts｜配鑽：天然鑽｜配鑽重量：22D:0.21cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "天然鑽",
    "mainStoneWeight": "D:0.30cts",
    "accentStone": "天然鑽",
    "accentStoneWeight": "22D:0.21cts",
    "metal": "14KW",
    "chainMetal": null,
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": false,
    "unavailableReason": "商品資料確認中"
  },
  {
    "id": "e-01",
    "sku": "ER00001-ER149",
    "name": "花語鑽石耳環\n(Floral Diamond Stud Earrings)",
    "category": "earrings",
    "materials": [
      "18k-rose-gold",
      "diamond"
    ],
    "styleTags": [
      "minimal",
      "refined"
    ],
    "price": 85000,
    "images": [
      "assets/missdiamond/earring/ER00001-ER149.jpg",
      "assets/missdiamond/earring/ER00001-ER149-2.jpg"
    ],
    "description": "將盛開的花朵化作耳畔的風景。\n花語鑽石耳環以八顆馬眼形天然鑽石排列出優雅花瓣輪廓，透過細膩比例與柔和線條，展現女性溫柔而自信的氣質。每一片花瓣在光線照射下綻放不同角度的火彩，讓耳際閃耀卻不過分張揚。\n18K玫瑰金溫潤色澤與鑽石光芒相互襯托，無論是日常穿搭、聚會場合，或作為紀念禮物，都能展現恰到好處的精緻感。\n花朵象徵成長與綻放，也提醒著我們，在每一個平凡的日子裡，都值得活出屬於自己的光彩。",
    "featureTags": [
      "經典款",
      "日常配戴",
      "紀念送禮"
    ],
    "specifications": "材質：18KR｜鍊材質：10K｜主石：天然鑽｜主石重量：無｜配鑽：天然鑽｜配鑽重量：MQ8P:0.68cts(0.085)",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "天然鑽",
    "mainStoneWeight": "無",
    "accentStone": "天然鑽",
    "accentStoneWeight": "MQ8P:0.68cts(0.085)",
    "metal": "18KR",
    "chainMetal": "10K",
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "e-02",
    "sku": "ER00002-H4",
    "name": "Tiny Spark｜18K白單鑽耳扣圈耳環",
    "category": "earrings",
    "materials": [
      "18k-white-gold",
      "diamond"
    ],
    "styleTags": [
      "sweet",
      "glamorous"
    ],
    "price": 28000,
    "images": [
      "assets/missdiamond/earring/ER00002-H4.jpg",
      "assets/missdiamond/earring/ER00002-H4-2.jpg"
    ],
    "description": "有些美，不需要張揚。\nTiny Spark 系列以最純粹的設計，讓天然鑽石成為每日陪伴的小亮點。纖細耳圈搭配輕盈鑽飾，不論是上班、約會或日常生活，都能自在配戴。\n是一款能陪伴妳許久、越戴越耐看的經典日常珠寶。",
    "featureTags": [
      "簡約百搭",
      "日常配戴",
      "俐落風格"
    ],
    "specifications": "材質：18KW｜主石：無｜主石重量：無｜配鑽：天然鑽｜配鑽重量：2D:0.03cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "無",
    "mainStoneWeight": "無",
    "accentStone": "天然鑽",
    "accentStoneWeight": "2D:0.03cts",
    "metal": "18KW",
    "chainMetal": null,
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "ER00003-H44",
    "sku": "ER00003-H44",
    "name": "Classic Brilliance\n14K 天然鑽石耳針",
    "category": "earrings",
    "materials": [
      "diamond"
    ],
    "styleTags": [],
    "price": 35000,
    "images": [
      "assets/missdiamond/earring/ER00003-H44.jpg"
    ],
    "description": "真正經典的珠寶，不會因流行而改變。\nClassic Brilliance 以俐落的四爪設計，讓光線能充分進入鑽石，展現自然璀璨的火彩。白K金細緻光澤與天然鑽石相互襯托，不論單獨佩戴或與其他耳飾層次搭配，都能散發優雅魅力。\n從第一副天然鑽石耳環，到陪伴多年的日常珠寶，它都值得收藏。",
    "featureTags": [
      "經典款",
      "簡約百搭",
      "日常配戴"
    ],
    "specifications": "材質：14KW｜主石：無｜配鑽：天然鑽｜配鑽重量：2D:0.16cts(0.08)",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "無",
    "mainStoneWeight": null,
    "accentStone": "天然鑽",
    "accentStoneWeight": "2D:0.16cts(0.08)",
    "metal": "14KW",
    "chainMetal": null,
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "ER00004-H6",
    "sku": "ER00004-H6",
    "name": "Tiny Spark｜18K玫瑰金單鑽耳扣圈耳環",
    "category": "earrings",
    "materials": [
      "18k-rose-gold",
      "diamond"
    ],
    "styleTags": [],
    "price": 25000,
    "images": [
      "assets/missdiamond/earring/ER00004-H6.jpg"
    ],
    "description": "有些美，不需要張揚。\nTiny Spark 系列以最純粹的設計，讓天然鑽石成為每日陪伴的小亮點。纖細耳圈搭配輕盈鑽飾，不論是上班、約會或日常生活，都能自在配戴。\n是一款能陪伴妳許久、越戴越耐看的經典日常珠寶。",
    "featureTags": [
      "簡約百搭",
      "日常配戴",
      "俐落風格"
    ],
    "specifications": "材質：18KR｜主石：無｜配鑽：天然鑽｜配鑽重量：2D:0.03cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "無",
    "mainStoneWeight": null,
    "accentStone": "天然鑽",
    "accentStoneWeight": "2D:0.03cts",
    "metal": "18KR",
    "chainMetal": null,
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "ER00005-PB396",
    "sku": "ER00005-PB396",
    "name": "心語1.5克拉滿鑽耳環",
    "category": "earrings",
    "materials": [
      "diamond"
    ],
    "styleTags": [],
    "price": 238300,
    "images": [
      "assets/missdiamond/earring/ER00005-PB396.jpg"
    ],
    "description": "愛心，是最經典也最耐看的珠寶元素。\n\n這款耳環以約1.5克拉天然鑽石密鑲打造，讓整個愛心輪廓綻放細膩而均勻的光澤；背面則採鏤空愛心設計，不僅減輕重量，也讓光線更容易穿透鑽石，使火光更加明亮。\n\n隨著走動微微擺動，每一次轉身都散發柔和而耀眼的光芒。無論作為紀念日禮物、生日贈禮，或犒賞自己的收藏，都能陪伴妳很長的時間。",
    "featureTags": [
      "日常配戴",
      "愛心設計",
      "輕盈舒適"
    ],
    "specifications": "材質：14KW｜配鑽：天然鑽｜配鑽重量：68D:1.50cts(0.02)",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": null,
    "mainStoneWeight": null,
    "accentStone": "天然鑽",
    "accentStoneWeight": "68D:1.50cts(0.02)",
    "metal": "14KW",
    "chainMetal": null,
    "stock": 1,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "m-01",
    "sku": "MR00001-DM00614",
    "name": "Royal Crown 鑽石男戒",
    "category": "mens-ring",
    "materials": [
      "diamond"
    ],
    "styleTags": [
      "neutral",
      "minimal"
    ],
    "price": 253800,
    "images": [
      "assets/missdiamond/man ring/MR00001-DM00614.jpg",
      "assets/missdiamond/man ring/MR00001-DM00614-2.jpg"
    ],
    "description": "以 81 顆天然鑽石鋪鑲而成，總鑽重達 1.27 克拉，展現大器且耀眼的視覺效果。\n\n寬版戒身結合立體幾何線條，中央主視覺採層次鑲嵌設計，使整體更具深度與光影變化。白K金的冷冽光澤與鑽石火光相互襯托，呈現沉穩而不失氣勢的男士珠寶風格。\n\n適合重視質感、喜歡份量感珠寶的男性配戴。",
    "featureTags": [
      "紀念送禮",
      "寬版設計",
      "立體層次"
    ],
    "specifications": "材質：白k金｜主石：無｜主石重量：無｜配鑽：天然鑽｜配鑽重量：81D:1.27cts(0.015)",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "無",
    "mainStoneWeight": "無",
    "accentStone": "天然鑽",
    "accentStoneWeight": "81D:1.27cts(0.015)",
    "metal": "白k金",
    "chainMetal": null,
    "stock": null,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  },
  {
    "id": "m-02",
    "sku": "MR00002-DM00616",
    "name": "Imperial Crown 皇家鋒芒男戒",
    "category": "mens-ring",
    "materials": [
      "diamond"
    ],
    "styleTags": [
      "bold",
      "designer"
    ],
    "price": 536100,
    "images": [
      "assets/missdiamond/man ring/MR00002-DM00616.jpg",
      "assets/missdiamond/man ring/MR00002-DM00616-2.jpg"
    ],
    "description": "如果說西裝代表男人的專業，那麼珠寶則象徵他的成就。\n\nImperial Crown 皇家鋒芒男戒，以大量天然真鑽鋪鑲打造強烈存在感。中央鑽石群鑲設計猶如聚光燈焦點，搭配層層向外延伸的建築感線條，展現沉穩、自信與領導者氣質。\n\n無論是商務宴會、重要場合，或作為人生里程碑的紀念珠寶，都能成為手上最醒目的焦點。",
    "featureTags": [
      "寬版設計",
      "立體層次",
      "細緻鑲嵌"
    ],
    "specifications": "材質：白k金｜主石：無｜主石重量：無｜配鑽：天然鑽｜配鑽重量：125D:2.38cts(0.019)",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": "無",
    "mainStoneWeight": "無",
    "accentStone": "天然鑽",
    "accentStoneWeight": "125D:2.38cts(0.019)",
    "metal": "白k金",
    "chainMetal": null,
    "stock": null,
    "sourceStatus": "歸還",
    "available": false,
    "unavailableReason": "目前暫不提供看貨媒合"
  },
  {
    "id": "MR00003-DM00458",
    "sku": "MR00003-DM00458",
    "name": "王者80分鑽石男戒",
    "category": "mens-ring",
    "materials": [
      "diamond"
    ],
    "styleTags": [],
    "price": 189300,
    "images": [
      "assets/missdiamond/man ring/MR00003-DM00458.jpg",
      "assets/missdiamond/man ring/MR00003-DM00458-2.jpg"
    ],
    "description": "真正有份量的魅力，不需要刻意張揚。\n\n33顆天然真鑽層層排列，將0.80克拉的璀璨凝聚於戒面之中，在不同光線下展現豐富而細緻的火彩。厚實的白K金戒身搭配俐落的方形設計，不僅提升整體立體感，也展現成熟穩重的品味。\n\n這不只是一枚鑽石男戒，更是一份對努力與成就的紀念。無論作為人生重要里程碑、自我犒賞，或是送給值得珍藏的人，都能陪伴歲月，見證每一段值得驕傲的時刻。",
    "featureTags": [
      "紀念送禮",
      "輕盈舒適",
      "俐落風格"
    ],
    "specifications": "材質：白k金｜配鑽：天然鑽｜配鑽重量：33D:0.80cts",
    "availableLocations": [
      "台北市",
      "新北市"
    ],
    "mainStone": null,
    "mainStoneWeight": null,
    "accentStone": "天然鑽",
    "accentStoneWeight": "33D:0.80cts",
    "metal": "白k金",
    "chainMetal": null,
    "stock": null,
    "sourceStatus": "寄店家",
    "available": true,
    "unavailableReason": null
  }
]

export const mockProducts: JewelryProduct[] = products.map(product => ({ ...product, images: product.images.map(path => import.meta.env.BASE_URL + path.split('/').map(encodeURIComponent).join('/')) }))
