import type { JewelryProduct } from '../types/product'

const image = (folder: string, name: string) => `${import.meta.env.BASE_URL}assets/missdiamond/${encodeURIComponent(folder)}/${encodeURIComponent(name)}`
const locations = ['台北', '台中', '高雄']

export const mockProducts: JewelryProduct[] = [
  { id: 'r-01', name: '晨曦單鑽戒', category: 'ring', materials: ['18k-white-gold', 'diamond'], styleTags: ['refined', 'minimal'], price: 68000, images: [image('ring', 'DR00002-PD394.jpg'), image('ring', 'DR00002-PD394-2.jpg')], description: '以簡淨戒台襯托主鑽光彩，適合重要的承諾時刻。', specifications: '18K 白金｜主鑽 0.50ct', availableLocations: locations },
  { id: 'r-02', name: '晴光花瓣戒', category: 'ring', materials: ['18k-rose-gold', 'diamond'], styleTags: ['sweet', 'designer'], price: 48000, images: [image('ring', 'DR00004-LN09.jpg'), image('ring', 'DR00004-LN09-2.jpg')], description: '柔和花瓣線條，為日常留下恰好的閃耀。', specifications: '18K 玫瑰金｜鑽石 0.28ct', availableLocations: ['台北', '台中'] },
  { id: 'r-03', name: '星軌鑽石戒', category: 'ring', materials: ['18k-yellow-gold', 'diamond'], styleTags: ['bold', 'glamorous'], price: 128000, images: [image('ring', 'DR00014-PD804.jpg'), image('ring', 'DR00014-PD804-2.jpg')], description: '環繞式鑽石排列，讓視線停留在每一次轉身。', specifications: '18K 黃金｜鑽石 1.05ct', availableLocations: locations },
  { id: 'e-01', name: '微光圓鑽耳釘', category: 'earrings', materials: ['18k-white-gold', 'diamond'], styleTags: ['minimal', 'refined'], price: 32000, images: [image('earring', 'ER00001-ER149.jpg'), image('earring', 'ER00001-ER149-2.jpg')], description: '貼耳的精緻光芒，適合每一個日常場合。', specifications: '18K 白金｜鑽石 0.20ct', availableLocations: ['台北', '高雄'] },
  { id: 'e-02', name: '月桂垂墜耳環', category: 'earrings', materials: ['18k-rose-gold', 'diamond'], styleTags: ['sweet', 'glamorous'], price: 76000, images: [image('earring', 'ER00002-H4.jpg'), image('earring', 'ER00002-H4-2.jpg')], description: '輕盈垂墜線條，為聚會與紀念日添上一點光。', specifications: '18K 玫瑰金｜鑽石 0.62ct', availableLocations: locations },
  { id: 'n-01', name: '流光單墜項鍊', category: 'necklace', materials: ['18k-white-gold', 'diamond'], styleTags: ['minimal', 'refined'], price: 42000, images: [image('pendant', 'DP00005-DP331.jpg'), image('pendant', 'DP00006-DP339.jpg')], description: '低調單墜設計，讓光在頸間安靜停留。', specifications: '18K 白金｜鑽石 0.30ct', availableLocations: locations },
  { id: 'n-02', name: '珊瑚粉鑽墜鍊', category: 'necklace', materials: ['18k-rose-gold', 'colored-gemstone'], styleTags: ['sweet', 'designer'], price: 58000, images: [image('pendant', 'DP00009-DP220R.jpg'), image('pendant', 'DP00011-DP221R.jpg')], description: '溫柔玫瑰色調，為送禮留下鮮明而不張揚的記憶。', specifications: '18K 玫瑰金｜彩色寶石', availableLocations: ['台北', '台中'] },
  { id: 'b-01', name: '星芒細鍊手鍊', category: 'bracelet', materials: ['18k-yellow-gold', 'diamond'], styleTags: ['minimal', 'sweet'], price: 36000, images: [image('braclet', 'BR00005-BR98.jpg'), image('braclet', 'BR00006-BR102.jpg')], description: '纖細鍊節與微鑽點綴，適合單戴或疊搭。', specifications: '18K 黃金｜鑽石 0.15ct', availableLocations: ['台北', '高雄'] },
  { id: 'b-02', name: '經典網球手鍊', category: 'bracelet', materials: ['18k-white-gold', 'diamond'], styleTags: ['refined', 'glamorous'], price: 168000, images: [image('braclet', 'BR00009-PB225.jpg'), image('braclet', 'BR00009-PB225-2.jpg')], description: '連續鑽石光帶，保留經典珠寶的雋永比例。', specifications: '18K 白金｜鑽石 1.80ct', availableLocations: locations },
  { id: 'm-01', name: '霧銀質感男戒', category: 'mens-ring', materials: ['18k-white-gold'], styleTags: ['neutral', 'minimal'], price: 52000, images: [image('man ring', 'MR00001-DM00614.jpg'), image('man ring', 'MR00001-DM00614-2.jpg')], description: '俐落霧面與拋光邊線，留給日常耐看的質感。', specifications: '18K 白金｜寬版戒身', availableLocations: locations },
  { id: 'm-02', name: '黑曜線條男戒', category: 'mens-ring', materials: ['18k-yellow-gold', 'colored-gemstone'], styleTags: ['bold', 'designer'], price: 88000, images: [image('man ring', 'MR00002-DM00616.jpg'), image('man ring', 'MR00002-DM00616-2.jpg')], description: '對比材質與立體切線，低調卻保有個性。', specifications: '18K 黃金｜黑色寶石', availableLocations: ['台北', '台中'] },
  { id: 'c-01', name: '相依素圈對戒', category: 'couple-ring', materials: ['platinum'], styleTags: ['minimal', 'neutral'], price: 62000, images: [image('band ring', 'DR00001-PD520.jpg'), image('band ring', 'DR00001-PD520-2.jpg')], description: '一對簡約鉑金戒，以日常佩戴的舒適為優先。', specifications: '鉑金｜對戒一組', availableLocations: locations },
  { id: 'c-02', name: '緞帶微鑽對戒', category: 'couple-ring', materials: ['18k-rose-gold', 'diamond'], styleTags: ['sweet', 'refined'], price: 78000, images: [image('band ring', 'DR00003-DR464L.jpg'), image('band ring', 'DR00003-DR464L-2.jpg')], description: '以弧線和微鑽記錄兩人的溫柔默契。', specifications: '18K 玫瑰金｜鑽石點綴', availableLocations: ['台北', '台中'] },
  { id: 'c-03', name: '交織光影對戒', category: 'couple-ring', materials: ['18k-yellow-gold', '18k-white-gold'], styleTags: ['designer', 'neutral'], price: 96000, images: [image('band ring', 'DR00007-DSR01.jpg'), image('band ring', 'DR00007-DSR01-2.jpg')], description: '雙色金屬交織，為彼此保留不同而相合的樣子。', specifications: '18K 雙色金｜對戒一組', availableLocations: locations },
  { id: 'c-04', name: '永恆密鑲對戒', category: 'couple-ring', materials: ['18k-white-gold', 'diamond'], styleTags: ['glamorous', 'refined'], price: 148000, images: [image('band ring', 'DR00010-PD636.jpg'), image('band ring', 'DR00010-PD636-2.jpg')], description: '密鑲鑽石細節，讓承諾在光線下被好好看見。', specifications: '18K 白金｜鑽石 0.72ct', availableLocations: locations },
]
